### ISSUE TITLE
request for a new release v0.2.16 (urgent)

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/ctapipe-extra#16]
Hi,
would be it possible to create a new release v0.2.16 with the present HEAD? 
This is necessary for the LST and NectarCAM reader.

Thanks!

Franca

**Comment by FrancaCassol** [comment]
Hi,
it seems to be a serious problem with this issue, I would appreciate very much to get an explanation about it. 

Thanks

Cheers
Franca

**Comment by maxnoe** [comment]
v0.2.16 was released last week.
