### ISSUE TITLE
Reference frame of camgeom fits files in ctapipe-extra/ctapipe_resources/

### ISSUE THREAD

**Issue by TjarkMiener** [cta-observatory/ctapipe-extra#17]
Which reference frame is used for the camgeom fits files in `ctapipe-extra/ctapipe_resources/`? Is it consistent for all camera types or are additional transformation needed? 

I'm currently reading the pixel positions from the fits and then rotating by 'PIX_ROT' (from the header). Is this the correct way?

I noticed that the FACT 'CAM_ROT' differs from 0.0. What is the difference between pixel and camera rotation?

Many thanks!

**Comment by maxnoe** [comment]
We are working on defining which reference frame ctapipe is using internally now, and how the reference frames of the currently operating telescopes can be transformed into that one and how to include these informations into the camgeom files.

FACT is inconsistent, as it is using the FACT reference frame, as where all the others should use the simtel reference frame

**Comment by maxnoe** [comment]
Currently, all camera geometries have to be defined in the simtel reference frame,
see: https://cta-observatory.github.io/ctapipe/api/ctapipe.coordinates.CameraFrame.html#ctapipe.coordinates.CameraFrame

**Comment by MaxNoe** [comment]
Currently, all camera geometries have to be defined in the simtel reference frame,
see: https://cta-observatory.github.io/ctapipe/api/ctapipe.coordinates.CameraFrame.html#ctapipe.coordinates.CameraFrame
